services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: jobmailer-backend
    ports:
      - "3001:3001"
    env_file:
      - ./server/.env
    environment:
      - PORT=3001
      - CLIENT_URL=http://72.61.105.71:8081
    volumes:
      - ./server/assets:/app/server/assets
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: jobmailer-frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
    restart: unless-stopped
